// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxstukpnpvqiwaupbwqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c3R1a3BucHZxaXdhdXBid3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjI3NjMsImV4cCI6MjA3MTU5ODc2M30.xg7jBA29UEgYkTJEt7IeTi01Az09ryFqeGWNcnsiGm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});